import { NextResponse } from "next/server";

import { parseConfigImportPayload } from "@/lib/config-transfer";
import { saveConfig } from "@/lib/store";

export async function POST(request: Request) {
  let payload: unknown;

  try {
    payload = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON payload." }, { status: 400 });
  }

  const nextConfig = parseConfigImportPayload(payload);
  if (!nextConfig) {
    return NextResponse.json(
      { error: "Invalid config file. Use a file generated by Config Export." },
      { status: 400 },
    );
  }

  const config = await saveConfig(nextConfig);
  return NextResponse.json({ config });
}
